name: electricity-demand-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - tensorflow
  - requests
  - scipy
  - pytest